language: cpp
compiler:
  - gcc

before_install:
  - wget https://github.com/npotts/Qt5-Travis-CI/raw/master/Qt5.txz
  - tar xfp Qt5.txz -C ${HOME}

install:
  - sudo apt-get update -q
  - sudo apt-get install build-essential

script:
  - export PATH="${HOME}/Qt5.3.2/bin:${PATH}"
  - which qmake
  - uname -a
  - qmake --version
  - pwd
  - ls *
  - ls -alh ${HOME}/Qt5.3.2/*
  - ../../Qt5.3.2/bin/qmake
  - vendor/../../Qt5.3.2/bin/qmake
  - make -j$(nproc)



#language: cpp
#os:
#  - osx
#  - linux
#compiler:
#  - gcc
#before_install: ./CI/travis.before_install.sh
#install: ./CI/travis.install.sh
#before_script:
#  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then PATH="/usr/local/opt/qt5/bin:$PATH"; fi
#script:
# - qmake-qt5
#  - make -j2
