language: cpp
compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -q
  - sudo apt-get install build-essential
  - cd ~
  - wget https://github.com/npotts/Qt5-Travis-CI/raw/master/Qt5.txz
  - tar xfp Qt5.txz

script:
  - export PATH="/home/travis/Qt5.3.2/bin:${PATH}"
  - which qmake
  - qmake --version
  - ls build
  - ls builds
  - ls -alh ~/Qt5.3.2/bin/qmake
  - make -j$(nproc)


#notifications:
  #    irc: 
  #   channels:
  #   - "chat.freenode.net#Tox-Qt-GUI"
  # on_success: always
  # on_failure: always
