language: cpp
compiler:
  - gcc
  - clang

install:
  - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install libqt5-dev qt5-qmake

script:
  - qt5-qmake
  - make -j$(nproc)


#notifications:
  #    irc: 
  #   channels:
  #   - "chat.freenode.net#Tox-Qt-GUI"
  # on_success: always
  # on_failure: always
