language: cpp
os:
  - osx
  - linux
compiler:
  - gcc
before_install: ./CI/travis.before_install.sh
install: ./CI/travis.install.sh
before_script:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then PATH="/usr/local/opt/qt5/bin:$PATH"; fi
script:
  - ls /usr/bin/*qmake*
  - ls /usr/local/bin/*qmake*
  - ls /usr/lib/qt5/bin/*qmake*
  - ls /usr/lib/qt5/*
  - which qmake
  - qmake-qt5 --version
  - qmake-qt5
  - make -j2
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4ed233d9013d611a1568
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
